### ISSUE TITLE
peer to peer code review: week 4;

### ISSUE THREAD

**Issue by kelwilson** [chelmerrox/my-portfolio#14]
- you really did a great job of implementing all the features on the Figma template.
- I think it's nice to put some padding on the hamburger icon and the close button icon, so it would be easier for users to click on it.

**Comment by r-ahmed2022** [comment]
Gr8 work, the portfolio looks amazing... 👏 . In my opinion, yes, a little effort with padding could be  better option

**Comment by chelmerrox** [comment]
Thanks for the review! 🙂
